" For pathogen.vim: auto load all plugins in .vim/bundle
runtime bundle/vim-pathogen/autoload/pathogen.vim
call pathogen#infect()

" Auto reload vimrc when editing it
autocmd! bufwritepost .vimrc source ~/.vimrc

syntax on
filetype on

colorscheme molokai

" setting backspace
set nocompatible
set backspace=indent,eol,start

set cursorline
set number
set hlsearch

set t_Co=256
set showcmd		" Show (partial) command in status line.
set tabstop=4
set shiftwidth=4
set hidden
set nostartofline
set autoindent
set cindent
set cinoptions=:0.5s,=0.5s
set laststatus=2

" setting encoding
set fileencodings=utf-8,big5,euc-jp,gbk,euc-kr,utf-bom,iso8859-1
set encoding=utf-8
set termencoding=utf-8

" setting keymap
nmap <C-N> :set nu!<CR>

nmap <silent> <F2> :call ToggleMouse()<CR>

" <F3> and <F4> was reserved for SrcExpl

nmap <silent> <F5> :bprevious<CR>
nmap <silent> <F6> :bnext<CR>
nmap <silent> <F7> :set hls!<CR>

" Open and close all the three plugins on the same time 
nmap <silent> <F8>  :TrinityToggleAll<CR> 
" Open and close the Source Explorer separately 
nmap <silent> <F9>  :TrinityToggleSourceExplorer<CR> 
" Open and close the Taglist separately 
nmap <silent> <F10> :TrinityToggleTagList<CR> 
" Open and close the NERD Tree separately 
nmap <silent> <F11> :TrinityToggleNERDTree<CR> 
nmap <F12> \be

" functions
function! ToggleMouse()
	if &mouse == 'a'
		set mouse=
		echo "Mouse usage disabled"
	else
		set mouse=a
		echo "Mouse usage enabled"
	endif
endfunction
