#!/bin/bash

if [ -x /usr/local/bin/brew ] && [ -f $(brew --prefix)/etc/bash_completion ]; then
	. $(brew --prefix)/etc/bash_completion
fi

# Case-insensitive tab completion
# http://superuser.com/questions/90196/case-insensitive-tab-completion-in-bash
bind "set completion-ignore-case on"
bind "set show-all-if-ambiguous on"

# Enable colors
export CLICOLOR=1
export PATH='/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin'

alias ll='ls -l'

# For Ubuntu/Debian
if [ -f /etc/skel/.bashrc ]; then
	. /etc/skel/.bashrc
fi
