set shell=/bin/bash
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo
Plugin 'tomasr/molokai'
Plugin 'emnh/taglist.vim'
Plugin 'jlanzarotta/bufexplorer'
"Plugin 'Valloric/YouCompleteMe'
Plugin 'Lokaltog/vim-powerline'
Plugin 'klen/python-mode'
Plugin 'dag/vim-fish'
Plugin 'honza/dockerfile.vim'
Plugin 'fatih/vim-go'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" Auto reload vimrc when editing it
autocmd! bufwritepost .vimrc source ~/.vimrc

:silent! colorscheme molokai
syntax on

" setting backspace
set backspace=indent,eol,start

set cursorline
set number
set hlsearch

set t_Co=256
set showcmd		" Show (partial) command in status line.
set tabstop=4
set shiftwidth=4
set hidden
set nostartofline
set autoindent
set cindent
set cinoptions=:0.5s,=0.5s
set laststatus=2
set ruler
set modeline

" setting encoding
set fileencodings=utf-8,big5,euc-jp,gbk,euc-kr,utf-bom,iso8859-1
set encoding=utf-8
set termencoding=utf-8

" [Setting keymap]
nmap <C-N> :set nu!<CR>

nmap <silent> <F2> :call ToggleMouse()<CR>
" <F3> and <F4> was reserved for SrcExpl
nmap <silent> <F5> :bprevious<CR>
nmap <silent> <F6> :bnext<CR>
nmap <silent> <F7> :set hls!<CR>
nmap <F12> \be

" [Functions]
function! ToggleMouse()
	if &mouse == 'a'
		set mouse=
		echo "Mouse usage disabled"
	else
		set mouse=a
		echo "Mouse usage enabled"
	endif
endfunction

" [Plugins]

" YouCompleteMe
"let g:ycm_global_ycm_extra_conf = '~/.vim/.ycm_extra_conf.py'
"let g:ycm_min_num_of_chars_for_completion = 2
"let g:ycm_min_num_identifier_candidate_chars = 0
"let g:ycm_register_as_syntastic_checker = 1
"let g:ycm_complete_in_comments = 0
"let g:ycm_complete_in_strings = 1
"let g:ycm_collect_identifiers_from_comments_and_strings = 0
"let g:ycm_collect_identifiers_from_tags_files = 0
let g:ycm_autoclose_preview_window_after_completion=1

" python-mode
let g:pymode_rope = 0
let g:pymode_folding = 0
let g:pymode_trim_whitespaces = 1
